export const portfolio = {
  name: 'Zoubida Lotfi',
  initials: 'ZL',
  role: 'Data Project Manager',
  location: 'Paris, France',
  email: 'zoubida.lotfi.work@gmail.com',
  phone: '+33 7 60 45 95 22',
  summary: "Je transforme des enjeux métier complexes en produits data fiables, gouvernés et prêts à passer à l’échelle.",
  profile: "Je pilote des projets data internationaux stratégiques au sein d’une architecture multi-couches, en partenariat avec Dun & Bradstreet. À l’interface du métier, de la data et des équipes techniques, je sécurise chaque étape — du besoin à la production — avec un même objectif : rendre la donnée claire, robuste et utile à la décision.",
  metrics: [
    { value: '40M', label: 'entreprises dans le datamart', note: 'Un actif data international critique' },
    { value: '17', label: 'releases pilotées / an', note: 'Qualification, production, suivi' },
    { value: '150+', label: 'réclamations résolues', note: 'Analyse de cause racine' },
    { value: '2', label: 'projets stratégiques / an', note: 'Contexte international multi-équipes' },
  ],
  experience: [
    {
      dates: 'Déc. 2023 — Aujourd’hui',
      company: 'Altares Dun & Bradstreet',
      location: 'La Défense, Île-de-France',
      title: 'Data Project Manager',
      intro: 'Pilotage de produits et flux data internationaux au service des décisions de crédit et de conformité.',
      highlights: [
        'Pilotage du cycle complet de projets data stratégiques : cadrage, qualification, production et post-release.',
        'Conception des mappings alimentant le datamart international et les flux XML clients.',
        'Conduite de 17 releases annuelles avec tests Go / No Go et continuité des produits data.',
        'Fiabilisation d’un datamart de près de 40 millions d’entreprises.',
        'Résolution de plus de 150 réclamations data, dont 20 % via des corrections structurelles.',
        'Alignement des besoins métier avec les contraintes d’architecture, de synchronisation et de qualité.',
      ],
    },
    {
      dates: 'Jan. 2023 — Oct. 2023',
      company: 'Altares Dun & Bradstreet',
      location: 'La Défense, Île-de-France',
      title: 'Data Analyst — Alternance',
      intro: 'Première immersion au cœur de la donnée B2B, de son analyse à sa restitution opérationnelle.',
      highlights: ['Analyse et traitement de données métier.', 'Reporting et exploration avec Oracle SQL et Power BI.', 'Collaboration avec des équipes data et métier dans un contexte international.'],
    },
  ],
  capabilities: [
    { number: '01', title: 'Orchestrer', text: 'Roadmaps, backlog, releases et coordination multi-équipes dans des environnements exigeants.', tags: ['Agile / Scrum', 'Jira', 'Confluence', 'BUILD to RUN'] },
    { number: '02', title: 'Fiabiliser', text: 'Gouvernance, synchronisation et qualité de données de bout en bout.', tags: ['Data quality', 'Go / No Go', 'Root cause', 'ETL / ELT'] },
    { number: '03', title: 'Traduire', text: 'Passer d’un besoin stratégique à une spécification data exploitable par les équipes techniques.', tags: ['Data mapping', 'User stories', 'Priorisation', 'Vulgarisation'] },
    { number: '04', title: 'Éclairer', text: 'Transformer les données en signaux lisibles pour accélérer la décision.', tags: ['Oracle SQL', 'Power BI', 'Datalakes', 'Reporting'] },
  ],
  education: [
    { school: 'EILCO', place: 'Calais, France', degree: 'Diplôme d’ingénieure en informatique', detail: 'Mineure Intelligence Artificielle : Machine Learning, Deep Learning, IA fiable et Big Data.' },
    { school: 'NTNU', place: 'Trondheim, Norvège', degree: 'Programme international', detail: 'Traitement des données et intelligence artificielle.' },
    { school: 'Classes préparatoires', place: 'France', degree: 'Classes préparatoires aux grandes écoles', detail: 'Formation scientifique intensive préparant aux écoles d’ingénieurs.' },
  ],
  languages: ['Français — C1/C2', 'Anglais — C1/C2'],
}
